version: '3.8'

services:
  symfony:
    build:
      context: ./backend/tfg_backend
      dockerfile: Dockerfile
    container_name: symfony
    ports:
      - "8000:80"
    volumes:
      - ./backend/tfg_backend:/var/www/html
    environment:
      - APP_ENV=dev
    networks:
      - tfg-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - symfony
    networks:
      - tfg-network
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173", "--method=GET"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  tfg-network:
    driver: bridge 